# Generated by Django 3.2 on 2023-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230104_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
